# Sandcastle Light

# Font rendering
font_size 12.5
text_composition_strategy 1.0 0
adjust_column_width -1

# The basic colors
foreground              #3a3630
background              #faf5ee
selection_foreground    #3a3630
selection_background    #c9dced

# Cursor colors
cursor                  #3a3630
cursor_text_color       #faf5ee

# URL underline color when hovering
url_color               #2a7ab5

# Kitty window border colors
active_border_color     #2a7ab5
inactive_border_color   #b0a99e
bell_border_color       #d68a20

# Tab bar colors
active_tab_foreground   #faf5ee
active_tab_background   #2a7ab5
inactive_tab_foreground #7a756c
inactive_tab_background #ece7e0
tab_bar_background      #faf5ee

# Colors for marks
mark1_foreground #faf5ee
mark1_background #2a7ab5
mark2_foreground #faf5ee
mark2_background #8a6aaa
mark3_foreground #faf5ee
mark3_background #3a8a4a

# The 16 terminal colors
# black
color0  #3a3630
color8  #7a756c

# red
color1  #c44040
color9  #d45555

# green
color2  #3a8a4a
color10 #4a9a5a

# yellow
color3  #a09000
color11 #b8a820

# blue
color4  #3a7a3a
color12 #4a8a4a

# magenta
color5  #8a6aaa
color13 #9a7aba

# cyan
color6  #b06888
color14 #c07898

# white
color7  #b0a99e
color15 #3a3630
